import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

import '../globals.css';
import DashboardNavbar from '@/DashboardNavbar';
import { redirect } from 'next/navigation';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';

const poppins = Poppins({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RoutesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  if (!session) {
    redirect('/login');
  }
  return (
    <html lang="en">
      <body className={poppins.className}>
        <DashboardNavbar />
        <main className="pl-72 pt-12 bg-primary min-h-screen">{children}</main>
      </body>
    </html>
  );
}
