import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import Provider from '@/app/_components/Provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <main className="h-svh bg-main flex justify-center items-center text-center">
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
