import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '../globals.css';
import Provider from '@/app/_components/Provider';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { redirect } from 'next/navigation';

const poppins = Poppins({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  if (session) {
    redirect('/dashboard');
  }
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Provider>
          <main className="h-svh bg-main flex justify-center items-center text-center">
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
